# ---- Build Stage ----
FROM maven:3.9.9-eclipse-temurin-17 AS build
WORKDIR /workspace

COPY pom.xml mvnw ./
COPY .mvn .mvn
RUN mvn -B -f pom.xml -ntp dependency:go-offline

COPY src ./src
RUN mvn -B clean package -DskipTests

# ---- Runtime Stage ----
FROM eclipse-temurin:17-jre-jammy
WORKDIR /app

# Build args
ARG SERVER_PORT=8080
ARG USER_SERVICE_URL
ARG CATALOG_SERVICE_URL
ARG SHOW_SERVICE_URL
ARG BOOKING_SERVICE_URL
ARG PAYMENT_SERVICE_URL
ARG NOTIFICATION_SERVICE_URL
ARG AUDIT_SERVICE_URL
ARG JWT_SECRET
ARG JWT_ISSUER
ARG JWT_EXPIRATION

# Bake into ENV
ENV SERVER_PORT=$SERVER_PORT \
    USER_SERVICE_URL=$USER_SERVICE_URL \
    CATALOG_SERVICE_URL=$CATALOG_SERVICE_URL \
    SHOW_SERVICE_URL=$SHOW_SERVICE_URL \
    BOOKING_SERVICE_URL=$BOOKING_SERVICE_URL \
    PAYMENT_SERVICE_URL=$PAYMENT_SERVICE_URL \
    NOTIFICATION_SERVICE_URL=$NOTIFICATION_SERVICE_URL \
    AUDIT_SERVICE_URL=$AUDIT_SERVICE_URL \
    JWT_SECRET=$JWT_SECRET \
    JWT_ISSUER=$JWT_ISSUER \
    JWT_EXPIRATION=$JWT_EXPIRATION

COPY --from=build /workspace/target/*.jar app.jar

EXPOSE ${SERVER_PORT}
ENTRYPOINT ["java","-jar","/app/app.jar"]
