name: Build and Push API Gateway

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build JAR
        run: mvn clean package -DskipTests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image (no cache)
        run: |
          echo "Building API Gateway Docker image..."
          docker buildx build . \
            --no-cache \
            --build-arg SERVER_PORT="8080" \
            --build-arg USER_SERVICE_URL="${{ secrets.USER_SERVICE_URL }}" \
            --build-arg CATALOG_SERVICE_URL="${{ secrets.CATALOG_SERVICE_URL }}" \
            --build-arg SHOW_SERVICE_URL="${{ secrets.SHOW_SERVICE_URL }}" \
            --build-arg BOOKING_SERVICE_URL="${{ secrets.BOOKING_SERVICE_URL }}" \
            --build-arg PAYMENT_SERVICE_URL="${{ secrets.PAYMENT_SERVICE_URL }}" \
            --build-arg NOTIFICATION_SERVICE_URL="${{ secrets.NOTIFICATION_SERVICE_URL }}" \
            --build-arg AUDIT_SERVICE_URL="${{ secrets.AUDIT_SERVICE_URL }}" \
            --build-arg JWT_SECRET="${{ secrets.JWT_SECRET }}" \
            --build-arg JWT_ISSUER="${{ secrets.JWT_ISSUER }}" \
            --build-arg JWT_EXPIRATION="${{ secrets.JWT_EXPIRATION }}" \
            -t "${{ secrets.DOCKER_USERNAME }}/eventura-api-gateway:latest" \
            --load

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/eventura-api-gateway:latest
